### ISSUE TITLE
Request for tool evaluation

### ISSUE THREAD

**Issue by dataf3l** [ligurio/awesome-ci#104]
Me and a couple friend have been working on this tool.
Maybe you guys can provide some feedback?
The idea is to make the most simple and basic ci tool possible.

https://github.com/dataf3l/hook

Will you Continuous Integration experts guide me as to how to improve it?

**Comment by ligurio** [comment]
I don't provide any tool evaluation here.

**Comment by dataf3l** [comment]
"Awesome!"

**Comment by ligurio** [comment]
@dataf3l take a look on https://github.com/adnanh/webhook

**Comment by dataf3l** [comment]
Thanks. Apologies for my earlier message, it may come as aggressive.
