### ISSUE TITLE
snap is no longer free for private repo

### ISSUE THREAD

**Issue by ratancs** [ligurio/awesome-ci#18]
https://snap-ci.com/my_plans/
private repos for as little as $30/mo

**Comment by ligurio** [comment]
AFAIU public repos are still for free but with limitations, so nothing to fix.

**Comment by ratancs** [comment]
Snap is Going Away

https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/

**Comment by ligurio** [comment]
It was removed.

**Comment by ligurio** [comment]
It was removed.
