### ISSUE TITLE
Githost Docs link 404s

### ISSUE THREAD

**Issue by StephenHodgson** [ligurio/awesome-ci#20]
The Githost Document link also 404s

**Comment by JayAndCatchFire** [comment]
This is also true of their pricing link.

If you go to their site and click on their documentation or pricing links, it just redirects to Gitlab.

Maybe Githost should be removed.  It looks kinda dead.

**Comment by JayAndCatchFire** [comment]
For posterity, https://github.com/ligurio/awesome-ci/commit/ed6ce61ca82c86e25139271b7a8e5bcb80d39cb2 solved my concern about Githost's pricing link.  😉
